const API_KEY_OMDBAPI = '1744ab12';
const API_KEY_NASA = 'TU_API_KEY';
const API_KEY_UNSPLASH = 'dSMva51jSuNIcuXROJLBqXZSi9A9hwXu2y-3LUC_S8E';

export { API_KEY_OMDBAPI, API_KEY_NASA, API_KEY_UNSPLASH };